#!/bin/bash

pushd "sintetizador"
RUSTFLAGS="-A warnings" cargo build
popd

mkdir -p "midi"
mkdir -p "wav"

# extrai apenas o nome do arquivo, removendo extensao e caminho
NOME=$(echo $1 | cut -d'.' -f1 | rev | cut -d'/' -f1 | rev)

# compilador.geraMidi()

ARG="midi/$NOME.mid"

sintetizador/target/debug/main $ARG