#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Uso: run <arquivo-entrada>"
    exit 1
fi

pushd "sintetizador"
echo "compilando sintetizador..."
RUSTFLAGS="-A warnings" cargo build
popd

# extrai apenas o nome do arquivo, removendo extensao e caminho
NOME=$(echo $1 | cut -d'.' -f1 | rev | cut -d'/' -f1 | rev)

echo "gerando midi..."
mkdir -p "midi"
# source venv/bin/activate
python3 -m compilador.main $1
MIDI="midi/$NOME.mid"

echo "sintetizando wav..."
mkdir -p "wav"
sintetizador/target/debug/main $MIDI